export const REGEX_ICON: any = Object.seal({
  email: "email",
  ssn: "default-view-open",
  ipAddress: "debug-disconnect",
  macAddress: "key",
  creditCard: "key",
  slackToken: "key",
  awsApiKey: "key",
  awsMwsAuthToken: "key",
  awsAppsyncGraphqlKey: "key",
  fbAccessToken: "key",
  fbOath: "key",
  github: "key",
  genericApiKey: "key",
  genericSecret: "key",
  googleApiKey: "key",
  gcpApiKey: "key",
  gcpOath: "key",
  gDriveApiKey: "key",
  gDriveOath: "key",
  gcpServiceKey: "key",
  gmailApiKey: "key",
  gmailOath: "key",
  gmailOathAccessToken: "key",
  youtubeApiKey: "key",
  youtubeOath: "key",
  herokuApiKey: "key",
  mailChimpApiKey: "key",
  mailGunApiKey: "key",
  passwordInUrl: "key",
  paypalKey: "key",
  picaticApiKey: "key",
  stripeApiKey: "key",
  stripeRestrictedApiKey: "key",
  squareAccessToken: "key",
  squareOath: "key",
  telegramBotApiKey: "key",
  twillioApiKey: "key",
  twitterAccessToken: "key",
  twitterOath: "key",
});

export const REGEX_ICON_KEYS = Object.keys(REGEX_ICON);
