export const REGEX_REASON: any = Object.seal({
  email: "Email address not allowed",
  ssn: "Social security number not allowed",
  ipAddress: "IP address not allowed",
  macAddress: "MAC address not allowed",
  creditCard: "Credit card number",
  slackToken: "Slack token",
  awsApiKey: "AWS api key",
  awsMwsAuthToken: "AWS MWS auth token",
  awsAppsyncGraphqlKey: "AWS AppSync Graphql key",
  fbAccessToken: "Facebook access token",
  fbOath: "Facebook Oath token",
  github: "Github token",
  genericApiKey: "Generic api key",
  genericSecret: "Generic secret",
  googleApiKey: "Google api key",
  gcpApiKey: "GCP api key",
  gcpOath: "GCP Oath token",
  gDriveApiKey: "Google drive api key",
  gDriveOath: "Google drive Oath token ",
  gcpServiceKey: "GCP service api key",
  gmailApiKey: "Gmail api key",
  gmailOath: "Gmail Oath token",
  gmailOathAccessToken: "Gmail Oath token",
  youtubeApiKey: "Youtube api key",
  youtubeOath: "Youtube Oath token",
  herokuApiKey: "Heroku api key",
  mailChimpApiKey: "Mail chimp api key",
  mailGunApiKey: "Mail gun api key",
  passwordInUrl: "Password in url",
  paypalKey: "Paypal api key",
  picaticApiKey: "Picatic api key",
  stripeApiKey: "Stripe api key",
  stripeRestrictedApiKey: "Stripe restricted api key",
  squareAccessToken: "Square access token",
  squareOath: "Square oath token",
  telegramBotApiKey: "Telegram bot api key",
  twillioApiKey: "Twillio api key",
  twitterAccessToken: "Twitter access token",
  twitterOath: "Twitter Oath token",
});

export const REGEX_REASON_KEYS = Object.keys(REGEX_REASON);
