export const REGEX_MESSAGE: any = Object.seal({
  email: "Contains a email address",
  ssn: "Contains a social security number",
  ipAddress: "Contains a IP address",
  macAddress: "Contains a MAC address",
  creditCard: "Contains a credit card number",
  slackToken: "Contains a slack token",
  awsApiKey: "Contains AWS api key",
  awsMwsAuthToken: "Contains AWS MWS auth token",
  awsAppsyncGraphqlKey: "Contains AWS AppSync Graphql key",
  fbAccessToken: "Contains facebook access token",
  fbOath: "Contains facebook Oath token",
  github: "Contains github token",
  genericApiKey: "Contains generic api key",
  genericSecret: "Contains generic secret",
  googleApiKey: "Contains google api key",
  gcpApiKey: "Contains GCP api key",
  gcpOath: "Contains GCP Oath token",
  gDriveApiKey: "Contains Google drive api key",
  gDriveOath: "Contains Google drive Oath token ",
  gcpServiceKey: "Contains GCP service api key",
  gmailApiKey: "Contains gmail api key",
  gmailOath: "Contains gmail Oath token",
  gmailOathAccessToken: "Contains gmail Oath token",
  youtubeApiKey: "Contains youtube api key",
  youtubeOath: "Contains youtube Oath token",
  herokuApiKey: "Contains heroku api key",
  mailChimpApiKey: "Contains mail chimp api key",
  mailGunApiKey: "Contains mail gun api key",
  passwordInUrl: "Contains password in url",
  paypalKey: "Contains paypal api key",
  picaticApiKey: "Contains picatic api key",
  stripeApiKey: "Contains stripe api key",
  stripeRestrictedApiKey: "Contains stripe restricted api key",
  squareAccessToken: "Contains square access token",
  squareOath: "Contains square oath token",
  telegramBotApiKey: "Contains telegram bot api key",
  twillioApiKey: "Contains twillio api key",
  twitterAccessToken: "Contains twitter access token",
  twitterOath: "Contains twitter Oath token",
});

export const REGEX_MESSAGE_KEYS = Object.keys(REGEX_MESSAGE);
