export const REGEX_LEVEL: any = Object.seal({
    email: "Warning",
    ssn: "Error",
    ipAddress: "Warning",
    macAddress: "Error",
    creditCard: "Warning",
    slackToken: "Warning",
    awsApiKey: "Warning",
    awsMwsAuthToken: "Warning",
    awsAppsyncGraphqlKey: "Warning",
    fbAccessToken: "Warning",
    fbOath: "Warning",
    github: "Warning",
    genericApiKey: "Warning",
    genericSecret: "Warning",
    googleApiKey: "Warning",
    gcpApiKey: "Warning",
    gcpOath: "Warning",
    gDriveApiKey: "Warning",
    gDriveOath: "Warning",
    gcpServiceKey: "Warning",
    gmailApiKey: "Warning",
    gmailOath: "Warning",
    gmailOathAccessToken: "Warning",
    youtubeApiKey: "Warning",
    youtubeOath: "Warning",
    herokuApiKey: "Warning",
    mailChimpApiKey: "Warning",
    mailGunApiKey: "Warning",
    passwordInUrl: "Warning",
    paypalKey: "Warning",
    picaticApiKey: "Warning",
    stripeApiKey: "Warning",
    stripeRestrictedApiKey: "Warning",
    squareAccessToken: "Warning",
    squareOath: "Warning",
    telegramBotApiKey: "Warning",
    twillioApiKey: "Warning",
    twitterAccessToken: "Warning",
    twitterOath: "Warning",
  });
  
  export const REGEX_LEVEL_KEYS = Object.keys(REGEX_LEVEL);